// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// read_bim_cpp
DataFrame read_bim_cpp(std::string bim_file);
RcppExport SEXP _polyvar_read_bim_cpp(SEXP bim_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bim_file(bim_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(read_bim_cpp(bim_file));
    return rcpp_result_gen;
END_RCPP
}
// read_fam_cpp
DataFrame read_fam_cpp(std::string fam_file);
RcppExport SEXP _polyvar_read_fam_cpp(SEXP fam_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fam_file(fam_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(read_fam_cpp(fam_file));
    return rcpp_result_gen;
END_RCPP
}
// read_bed_batch_cpp
NumericMatrix read_bed_batch_cpp(std::string bed_file, int n_indiv, int snp_start, int snp_count);
RcppExport SEXP _polyvar_read_bed_batch_cpp(SEXP bed_fileSEXP, SEXP n_indivSEXP, SEXP snp_startSEXP, SEXP snp_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bed_file(bed_fileSEXP);
    Rcpp::traits::input_parameter< int >::type n_indiv(n_indivSEXP);
    Rcpp::traits::input_parameter< int >::type snp_start(snp_startSEXP);
    Rcpp::traits::input_parameter< int >::type snp_count(snp_countSEXP);
    rcpp_result_gen = Rcpp::wrap(read_bed_batch_cpp(bed_file, n_indiv, snp_start, snp_count));
    return rcpp_result_gen;
END_RCPP
}
// read_bed_snp_cpp
NumericVector read_bed_snp_cpp(std::string bed_file, int n_indiv, int snp_idx);
RcppExport SEXP _polyvar_read_bed_snp_cpp(SEXP bed_fileSEXP, SEXP n_indivSEXP, SEXP snp_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bed_file(bed_fileSEXP);
    Rcpp::traits::input_parameter< int >::type n_indiv(n_indivSEXP);
    Rcpp::traits::input_parameter< int >::type snp_idx(snp_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(read_bed_snp_cpp(bed_file, n_indiv, snp_idx));
    return rcpp_result_gen;
END_RCPP
}
// make_phi_inv
NumericVector make_phi_inv(int n);
RcppExport SEXP _polyvar_make_phi_inv(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(make_phi_inv(n));
    return rcpp_result_gen;
END_RCPP
}
// standardise_geno
List standardise_geno(NumericVector g_raw);
RcppExport SEXP _polyvar_standardise_geno(SEXP g_rawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type g_raw(g_rawSEXP);
    rcpp_result_gen = Rcpp::wrap(standardise_geno(g_raw));
    return rcpp_result_gen;
END_RCPP
}
// ols_resid
List ols_resid(NumericVector r, NumericVector g_star);
RcppExport SEXP _polyvar_ols_resid(SEXP rSEXP, SEXP g_starSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g_star(g_starSEXP);
    rcpp_result_gen = Rcpp::wrap(ols_resid(r, g_star));
    return rcpp_result_gen;
END_RCPP
}
// apply_rint
NumericVector apply_rint(NumericVector e, NumericVector phi_inv);
RcppExport SEXP _polyvar_apply_rint(SEXP eSEXP, SEXP phi_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_inv(phi_invSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_rint(e, phi_inv));
    return rcpp_result_gen;
END_RCPP
}
// get_groups
List get_groups(NumericVector g_raw);
RcppExport SEXP _polyvar_get_groups(SEXP g_rawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type g_raw(g_rawSEXP);
    rcpp_result_gen = Rcpp::wrap(get_groups(g_raw));
    return rcpp_result_gen;
END_RCPP
}
// levene_rint_cpp
List levene_rint_cpp(NumericVector e_rint, IntegerVector grp_idx0, IntegerVector grp_idx1, IntegerVector grp_idx2);
RcppExport SEXP _polyvar_levene_rint_cpp(SEXP e_rintSEXP, SEXP grp_idx0SEXP, SEXP grp_idx1SEXP, SEXP grp_idx2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type e_rint(e_rintSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx0(grp_idx0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx1(grp_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx2(grp_idx2SEXP);
    rcpp_result_gen = Rcpp::wrap(levene_rint_cpp(e_rint, grp_idx0, grp_idx1, grp_idx2));
    return rcpp_result_gen;
END_RCPP
}
// levene_norint_cpp
List levene_norint_cpp(NumericVector e_ols, IntegerVector grp_idx0, IntegerVector grp_idx1, IntegerVector grp_idx2);
RcppExport SEXP _polyvar_levene_norint_cpp(SEXP e_olsSEXP, SEXP grp_idx0SEXP, SEXP grp_idx1SEXP, SEXP grp_idx2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type e_ols(e_olsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx0(grp_idx0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx1(grp_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx2(grp_idx2SEXP);
    rcpp_result_gen = Rcpp::wrap(levene_norint_cpp(e_ols, grp_idx0, grp_idx1, grp_idx2));
    return rcpp_result_gen;
END_RCPP
}
// bf_norint_cpp
List bf_norint_cpp(NumericVector e_ols, IntegerVector grp_idx0, IntegerVector grp_idx1, IntegerVector grp_idx2);
RcppExport SEXP _polyvar_bf_norint_cpp(SEXP e_olsSEXP, SEXP grp_idx0SEXP, SEXP grp_idx1SEXP, SEXP grp_idx2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type e_ols(e_olsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx0(grp_idx0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx1(grp_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx2(grp_idx2SEXP);
    rcpp_result_gen = Rcpp::wrap(bf_norint_cpp(e_ols, grp_idx0, grp_idx1, grp_idx2));
    return rcpp_result_gen;
END_RCPP
}
// bf_rint_cpp
List bf_rint_cpp(NumericVector e_rint, IntegerVector grp_idx0, IntegerVector grp_idx1, IntegerVector grp_idx2);
RcppExport SEXP _polyvar_bf_rint_cpp(SEXP e_rintSEXP, SEXP grp_idx0SEXP, SEXP grp_idx1SEXP, SEXP grp_idx2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type e_rint(e_rintSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx0(grp_idx0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx1(grp_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx2(grp_idx2SEXP);
    rcpp_result_gen = Rcpp::wrap(bf_rint_cpp(e_rint, grp_idx0, grp_idx1, grp_idx2));
    return rcpp_result_gen;
END_RCPP
}
// bartlett_rint_cpp
List bartlett_rint_cpp(NumericVector e_rint, IntegerVector grp_idx0, IntegerVector grp_idx1, IntegerVector grp_idx2);
RcppExport SEXP _polyvar_bartlett_rint_cpp(SEXP e_rintSEXP, SEXP grp_idx0SEXP, SEXP grp_idx1SEXP, SEXP grp_idx2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type e_rint(e_rintSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx0(grp_idx0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx1(grp_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_idx2(grp_idx2SEXP);
    rcpp_result_gen = Rcpp::wrap(bartlett_rint_cpp(e_rint, grp_idx0, grp_idx1, grp_idx2));
    return rcpp_result_gen;
END_RCPP
}
// dglm_cpp
List dglm_cpp(NumericVector r, NumericVector g_star, int max_iter);
RcppExport SEXP _polyvar_dglm_cpp(SEXP rSEXP, SEXP g_starSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g_star(g_starSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(dglm_cpp(r, g_star, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// polyvar_scores_cpp
List polyvar_scores_cpp(NumericVector e_rint, NumericVector g_star, double beta_hat);
RcppExport SEXP _polyvar_polyvar_scores_cpp(SEXP e_rintSEXP, SEXP g_starSEXP, SEXP beta_hatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type e_rint(e_rintSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g_star(g_starSEXP);
    Rcpp::traits::input_parameter< double >::type beta_hat(beta_hatSEXP);
    rcpp_result_gen = Rcpp::wrap(polyvar_scores_cpp(e_rint, g_star, beta_hat));
    return rcpp_result_gen;
END_RCPP
}
// polyvar_calibrate_cpp
List polyvar_calibrate_cpp(double T_C, double beta_hat, NumericVector lut_beta, NumericVector lut_q95);
RcppExport SEXP _polyvar_polyvar_calibrate_cpp(SEXP T_CSEXP, SEXP beta_hatSEXP, SEXP lut_betaSEXP, SEXP lut_q95SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type T_C(T_CSEXP);
    Rcpp::traits::input_parameter< double >::type beta_hat(beta_hatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lut_beta(lut_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lut_q95(lut_q95SEXP);
    rcpp_result_gen = Rcpp::wrap(polyvar_calibrate_cpp(T_C, beta_hat, lut_beta, lut_q95));
    return rcpp_result_gen;
END_RCPP
}
// polyvar_lite_setup_cpp
List polyvar_lite_setup_cpp(NumericVector r, int Q);
RcppExport SEXP _polyvar_polyvar_lite_setup_cpp(SEXP rSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(polyvar_lite_setup_cpp(r, Q));
    return rcpp_result_gen;
END_RCPP
}
// polyvar_lite_stat_cpp
List polyvar_lite_stat_cpp(NumericVector r, NumericVector g_star, double beta_hat, NumericVector breaks, NumericVector bin_q);
RcppExport SEXP _polyvar_polyvar_lite_stat_cpp(SEXP rSEXP, SEXP g_starSEXP, SEXP beta_hatSEXP, SEXP breaksSEXP, SEXP bin_qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g_star(g_starSEXP);
    Rcpp::traits::input_parameter< double >::type beta_hat(beta_hatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bin_q(bin_qSEXP);
    rcpp_result_gen = Rcpp::wrap(polyvar_lite_stat_cpp(r, g_star, beta_hat, breaks, bin_q));
    return rcpp_result_gen;
END_RCPP
}
// vqtl_batch_cpp
DataFrame vqtl_batch_cpp(NumericMatrix G, NumericVector r, NumericVector phi_inv, std::string method, NumericVector lut_beta, NumericVector lut_q95, int Q_lite, int dglm_iter);
RcppExport SEXP _polyvar_vqtl_batch_cpp(SEXP GSEXP, SEXP rSEXP, SEXP phi_invSEXP, SEXP methodSEXP, SEXP lut_betaSEXP, SEXP lut_q95SEXP, SEXP Q_liteSEXP, SEXP dglm_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_inv(phi_invSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lut_beta(lut_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lut_q95(lut_q95SEXP);
    Rcpp::traits::input_parameter< int >::type Q_lite(Q_liteSEXP);
    Rcpp::traits::input_parameter< int >::type dglm_iter(dglm_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(vqtl_batch_cpp(G, r, phi_inv, method, lut_beta, lut_q95, Q_lite, dglm_iter));
    return rcpp_result_gen;
END_RCPP
}
// polyvar_full_cpp
List polyvar_full_cpp(NumericVector r, NumericVector g_raw, NumericVector phi_inv);
RcppExport SEXP _polyvar_polyvar_full_cpp(SEXP rSEXP, SEXP g_rawSEXP, SEXP phi_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g_raw(g_rawSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_inv(phi_invSEXP);
    rcpp_result_gen = Rcpp::wrap(polyvar_full_cpp(r, g_raw, phi_inv));
    return rcpp_result_gen;
END_RCPP
}
// polyvar_lite_setup_fast
List polyvar_lite_setup_fast(NumericVector r, int Q);
RcppExport SEXP _polyvar_polyvar_lite_setup_fast(SEXP rSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(polyvar_lite_setup_fast(r, Q));
    return rcpp_result_gen;
END_RCPP
}
// polyvar_lite_fast
List polyvar_lite_fast(NumericVector r, NumericVector g_raw, NumericVector breaks, NumericVector bin_q);
RcppExport SEXP _polyvar_polyvar_lite_fast(SEXP rSEXP, SEXP g_rawSEXP, SEXP breaksSEXP, SEXP bin_qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g_raw(g_rawSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bin_q(bin_qSEXP);
    rcpp_result_gen = Rcpp::wrap(polyvar_lite_fast(r, g_raw, breaks, bin_q));
    return rcpp_result_gen;
END_RCPP
}
// polyvar_scan_cpp
DataFrame polyvar_scan_cpp(NumericMatrix G, NumericVector r, NumericVector phi_inv, NumericVector breaks, NumericVector bin_q, bool use_lite, NumericVector lut_beta, NumericVector lut_q95, double min_maf);
RcppExport SEXP _polyvar_polyvar_scan_cpp(SEXP GSEXP, SEXP rSEXP, SEXP phi_invSEXP, SEXP breaksSEXP, SEXP bin_qSEXP, SEXP use_liteSEXP, SEXP lut_betaSEXP, SEXP lut_q95SEXP, SEXP min_mafSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_inv(phi_invSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bin_q(bin_qSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lite(use_liteSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lut_beta(lut_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lut_q95(lut_q95SEXP);
    Rcpp::traits::input_parameter< double >::type min_maf(min_mafSEXP);
    rcpp_result_gen = Rcpp::wrap(polyvar_scan_cpp(G, r, phi_inv, breaks, bin_q, use_lite, lut_beta, lut_q95, min_maf));
    return rcpp_result_gen;
END_RCPP
}
// all_methods_scan_cpp
DataFrame all_methods_scan_cpp(NumericMatrix G, NumericVector r, NumericVector phi_inv, NumericVector breaks, NumericVector bin_q, NumericVector lut_beta, NumericVector lut_q95, double min_maf);
RcppExport SEXP _polyvar_all_methods_scan_cpp(SEXP GSEXP, SEXP rSEXP, SEXP phi_invSEXP, SEXP breaksSEXP, SEXP bin_qSEXP, SEXP lut_betaSEXP, SEXP lut_q95SEXP, SEXP min_mafSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_inv(phi_invSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bin_q(bin_qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lut_beta(lut_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lut_q95(lut_q95SEXP);
    Rcpp::traits::input_parameter< double >::type min_maf(min_mafSEXP);
    rcpp_result_gen = Rcpp::wrap(all_methods_scan_cpp(G, r, phi_inv, breaks, bin_q, lut_beta, lut_q95, min_maf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_polyvar_read_bim_cpp", (DL_FUNC) &_polyvar_read_bim_cpp, 1},
    {"_polyvar_read_fam_cpp", (DL_FUNC) &_polyvar_read_fam_cpp, 1},
    {"_polyvar_read_bed_batch_cpp", (DL_FUNC) &_polyvar_read_bed_batch_cpp, 4},
    {"_polyvar_read_bed_snp_cpp", (DL_FUNC) &_polyvar_read_bed_snp_cpp, 3},
    {"_polyvar_make_phi_inv", (DL_FUNC) &_polyvar_make_phi_inv, 1},
    {"_polyvar_standardise_geno", (DL_FUNC) &_polyvar_standardise_geno, 1},
    {"_polyvar_ols_resid", (DL_FUNC) &_polyvar_ols_resid, 2},
    {"_polyvar_apply_rint", (DL_FUNC) &_polyvar_apply_rint, 2},
    {"_polyvar_get_groups", (DL_FUNC) &_polyvar_get_groups, 1},
    {"_polyvar_levene_rint_cpp", (DL_FUNC) &_polyvar_levene_rint_cpp, 4},
    {"_polyvar_levene_norint_cpp", (DL_FUNC) &_polyvar_levene_norint_cpp, 4},
    {"_polyvar_bf_norint_cpp", (DL_FUNC) &_polyvar_bf_norint_cpp, 4},
    {"_polyvar_bf_rint_cpp", (DL_FUNC) &_polyvar_bf_rint_cpp, 4},
    {"_polyvar_bartlett_rint_cpp", (DL_FUNC) &_polyvar_bartlett_rint_cpp, 4},
    {"_polyvar_dglm_cpp", (DL_FUNC) &_polyvar_dglm_cpp, 3},
    {"_polyvar_polyvar_scores_cpp", (DL_FUNC) &_polyvar_polyvar_scores_cpp, 3},
    {"_polyvar_polyvar_calibrate_cpp", (DL_FUNC) &_polyvar_polyvar_calibrate_cpp, 4},
    {"_polyvar_polyvar_lite_setup_cpp", (DL_FUNC) &_polyvar_polyvar_lite_setup_cpp, 2},
    {"_polyvar_polyvar_lite_stat_cpp", (DL_FUNC) &_polyvar_polyvar_lite_stat_cpp, 5},
    {"_polyvar_vqtl_batch_cpp", (DL_FUNC) &_polyvar_vqtl_batch_cpp, 8},
    {"_polyvar_polyvar_full_cpp", (DL_FUNC) &_polyvar_polyvar_full_cpp, 3},
    {"_polyvar_polyvar_lite_setup_fast", (DL_FUNC) &_polyvar_polyvar_lite_setup_fast, 2},
    {"_polyvar_polyvar_lite_fast", (DL_FUNC) &_polyvar_polyvar_lite_fast, 4},
    {"_polyvar_polyvar_scan_cpp", (DL_FUNC) &_polyvar_polyvar_scan_cpp, 9},
    {"_polyvar_all_methods_scan_cpp", (DL_FUNC) &_polyvar_all_methods_scan_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_polyvar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
