# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_bim_cpp <- function(bim_file) {
    .Call(`_polyvar_read_bim_cpp`, bim_file)
}

read_fam_cpp <- function(fam_file) {
    .Call(`_polyvar_read_fam_cpp`, fam_file)
}

read_bed_batch_cpp <- function(bed_file, n_indiv, snp_start, snp_count) {
    .Call(`_polyvar_read_bed_batch_cpp`, bed_file, n_indiv, snp_start, snp_count)
}

read_bed_snp_cpp <- function(bed_file, n_indiv, snp_idx) {
    .Call(`_polyvar_read_bed_snp_cpp`, bed_file, n_indiv, snp_idx)
}

make_phi_inv <- function(n) {
    .Call(`_polyvar_make_phi_inv`, n)
}

standardise_geno <- function(g_raw) {
    .Call(`_polyvar_standardise_geno`, g_raw)
}

ols_resid <- function(r, g_star) {
    .Call(`_polyvar_ols_resid`, r, g_star)
}

apply_rint <- function(e, phi_inv) {
    .Call(`_polyvar_apply_rint`, e, phi_inv)
}

get_groups <- function(g_raw) {
    .Call(`_polyvar_get_groups`, g_raw)
}

levene_rint_cpp <- function(e_rint, grp_idx0, grp_idx1, grp_idx2) {
    .Call(`_polyvar_levene_rint_cpp`, e_rint, grp_idx0, grp_idx1, grp_idx2)
}

levene_norint_cpp <- function(e_ols, grp_idx0, grp_idx1, grp_idx2) {
    .Call(`_polyvar_levene_norint_cpp`, e_ols, grp_idx0, grp_idx1, grp_idx2)
}

bf_norint_cpp <- function(e_ols, grp_idx0, grp_idx1, grp_idx2) {
    .Call(`_polyvar_bf_norint_cpp`, e_ols, grp_idx0, grp_idx1, grp_idx2)
}

bf_rint_cpp <- function(e_rint, grp_idx0, grp_idx1, grp_idx2) {
    .Call(`_polyvar_bf_rint_cpp`, e_rint, grp_idx0, grp_idx1, grp_idx2)
}

bartlett_rint_cpp <- function(e_rint, grp_idx0, grp_idx1, grp_idx2) {
    .Call(`_polyvar_bartlett_rint_cpp`, e_rint, grp_idx0, grp_idx1, grp_idx2)
}

dglm_cpp <- function(r, g_star, max_iter = 10L) {
    .Call(`_polyvar_dglm_cpp`, r, g_star, max_iter)
}

polyvar_scores_cpp <- function(e_rint, g_star, beta_hat) {
    .Call(`_polyvar_polyvar_scores_cpp`, e_rint, g_star, beta_hat)
}

polyvar_calibrate_cpp <- function(T_C, beta_hat, lut_beta, lut_q95) {
    .Call(`_polyvar_polyvar_calibrate_cpp`, T_C, beta_hat, lut_beta, lut_q95)
}

polyvar_lite_setup_cpp <- function(r, Q = 100L) {
    .Call(`_polyvar_polyvar_lite_setup_cpp`, r, Q)
}

polyvar_lite_stat_cpp <- function(r, g_star, beta_hat, breaks, bin_q) {
    .Call(`_polyvar_polyvar_lite_stat_cpp`, r, g_star, beta_hat, breaks, bin_q)
}

vqtl_batch_cpp <- function(G, r, phi_inv, method, lut_beta, lut_q95, Q_lite = 100L, dglm_iter = 10L) {
    .Call(`_polyvar_vqtl_batch_cpp`, G, r, phi_inv, method, lut_beta, lut_q95, Q_lite, dglm_iter)
}

polyvar_full_cpp <- function(r, g_raw, phi_inv) {
    .Call(`_polyvar_polyvar_full_cpp`, r, g_raw, phi_inv)
}

polyvar_lite_setup_fast <- function(r, Q = 100L) {
    .Call(`_polyvar_polyvar_lite_setup_fast`, r, Q)
}

polyvar_lite_fast <- function(r, g_raw, breaks, bin_q) {
    .Call(`_polyvar_polyvar_lite_fast`, r, g_raw, breaks, bin_q)
}

polyvar_scan_cpp <- function(G, r, phi_inv, breaks, bin_q, use_lite, lut_beta, lut_q95, min_maf = 0.01) {
    .Call(`_polyvar_polyvar_scan_cpp`, G, r, phi_inv, breaks, bin_q, use_lite, lut_beta, lut_q95, min_maf)
}

all_methods_scan_cpp <- function(G, r, phi_inv, breaks, bin_q, lut_beta, lut_q95, min_maf = 0.01) {
    .Call(`_polyvar_all_methods_scan_cpp`, G, r, phi_inv, breaks, bin_q, lut_beta, lut_q95, min_maf)
}

